name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push-to-release-branch:
    name: Push source to release branch
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # we want all history because we use it to create the release branches
        fetch-depth: 0
        # we can't use the default token coming with the action cause GH prevents from create or updating workflows
        # which might be part of the release contents
        token: ${{ secrets.RELEASE_GITHUB_ACCESS_TOKEN }}
    - name: Push to release branch
      run: |
        export tag=$(echo ${GITHUB_REF#refs/tags/})
        export tag_suffix=$(echo ${tag%.*}.x)
        export branch_name=$(echo release/$tag_suffix)
        git fetch origin $branch_name || exit_code=$?
        if [[ $exit_code -eq 0 ]]; \
          then \
            echo "Branch $branch_name exists. Adding changes"; \
            git checkout $branch_name; \
            git merge $tag; \
          else \
            echo "Creating new branch: $branch_name"; \
            git checkout -b $branch_name; \
        fi
        git push origin $branch_name
